// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yijirheucyufndnoxtyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpamlyaGV1Y3l1Zm5kbm94dHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzgxNDQsImV4cCI6MjA2NTkxNDE0NH0.srVYRXDbe4QMPgYjYDrVAbQwd4uTGzQmYFaXan6iOPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);